# ============================================================================ #
# Author: Tancredi-Paul Grozav <paul@grozav.info>
# ============================================================================ #
name: Build .iso

# Triggers the workflow on push to the 'main' branch
on:
  push:
    branches:
    - main
    paths:
    - .github/workflows/build_iso.yml
    - ci/build_iso.sh
    - ci/embedded.ipxe
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run
# in-progress and latest queued. However, do NOT cancel in-progress runs as we
# want to allow these production deployments to complete.
concurrency:
  group: pages
  cancel-in-progress: false

env:
  LC_ALL: C.UTF-8

jobs:
  # Build job
  build:
    # runs-on: self-hosted
    # Uses a free GitHub runner
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    steps:
    # Must install git before checkout, otherwise .git folder is missing and
    # will just use REST API (download .zip of repo)
    - name: Install tools
      run: |
        set -x &&
        apk add --no-cache \
          ` # tar - to create the artifact ` \
          tar \
          ` # git - clone ipxe project ` \
          git \
          &&
        git --version &&
        true
    - name: Checkout
      uses: actions/checkout@v4
      with:
        # Fetches the entire history for git diff - not a shallow clone
        fetch-depth: 0
    - name: Setup Pages
      uses: actions/configure-pages@v5
    - name: Build .iso file
      run: sh ci/build_iso.sh
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ipxe/src/bin/ipxe.iso
        name: 'ISO Release - ${{ github.ref_name }}'
        tag_name: 'v${{ github.run_number }}'
        body: 'Automatic release of ISO artifact.'
    - name: Delete Old Releases
      uses: s00d/delete-older-releases0.2.1
      with:
        keep_latest: 3
        delete_type: release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
# ============================================================================ #
